import type { NextPage } from 'next'
import Head from 'next/head'
import { ErrorBoundary } from 'react-error-boundary'
import { Fallback } from '@components/Fallback/Fallback'
import { AccountForm } from './components/AccountForm/AccountForm'
import { Tabs as StyledTabs } from '@components/Tabs/Tabs.style'
import { Tabs } from '@components/Tabs/Tabs'
import { UpdateProfile } from './components/UpdateProfile/UpdateProfile'
import * as S from '@styles/common.style'
import { SettingsCard } from '@modules/Settings/Settings.style'

// export type Resource = {
//   id: string
//   type: string
//   title: string
//   summary: string
//   resource: string
//   isFeatured: boolean
// }

// export type ResourcesType = Resource[]

const panels: [React.ReactNode, React.ReactNode, React.ReactNode, React.ReactNode] = [
  <>
    <UpdateProfile />
    <AccountForm />
    <h3>Close your account</h3>
    <p>To close your account, please click here</p>
  </>,
  <div key=''>Notifications content</div>,
  <div key=''>Security content</div>,
  <div key=''>Donations content</div>,
]

const Settings: NextPage = () => {
  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <ErrorBoundary fallbackRender={({ error }) => <Fallback error={error?.message} />}>
        <S.Content>
          <SettingsCard>
            <h2>Settings</h2>
            <StyledTabs>
              <Tabs
                tabs={['Account', 'Notifications', 'Security', 'Donate']}
                panels={panels}
              ></Tabs>
            </StyledTabs>
          </SettingsCard>
        </S.Content>
      </ErrorBoundary>
    </>
  )
}

export default Settings
