import type { NextPage } from 'next'
import Head from 'next/head'
import { ErrorBoundary } from 'react-error-boundary'
import { Fallback } from '@components/Fallback/Fallback'
import { Hero } from '@components/Hero/Hero'
import { SwitchingJourney } from '@components/SwitchingJourney/SwitchingJourney'
import { Card } from '@components/Card/Card'
import { Blog } from '@components/Blog/Blog'
import * as S from '@styles/common.style'
import { Posts } from '@pages/dashboard'

type PageProps = {
  data: {
    posts: Posts
  }
}

const Dashboard: NextPage<PageProps> = ({ data: { posts = [] } = {} }: any) => {
  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <ErrorBoundary fallbackRender={({ error }) => <Fallback error={error?.message} />}>
        <S.Content>
          <Hero />
          <S.ColumnContainer>
            <S.Column>
              <Card>
                <Blog data={posts} />
              </Card>
            </S.Column>
            <S.Column>
              <Card>
                <SwitchingJourney title='Banks' text='4/5 steps' image='placeholder.png' />
              </Card>
            </S.Column>
            <S.Column>
              <Card>
                <SwitchingJourney title='Banks' text='4/5 steps' image='placeholder.png' />
              </Card>
            </S.Column>
          </S.ColumnContainer>
        </S.Content>
      </ErrorBoundary>
    </>
  )
}

export default Dashboard
