import type { NextPage } from 'next'
import Head from 'next/head'
import { User } from '@components/User/User'
import { Hero } from '@components/Hero/Hero'
import { SwitchingJourney } from '@components/SwitchingJourney/SwitchingJourney'
import * as S from '@modules/Dashboard/Dashboard.style'

type PageProps = {
  userData: any
}

const Dashboard: NextPage<PageProps> = ({ userData }: any) => {
  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <>
        <S.Content>
          <Hero />
          <S.SwitchingJourney>
            <S.Header>Switching Journeys</S.Header>
            <SwitchingJourney title='Banks' text='4/5 steps' image='placeholder.png' />
            <SwitchingJourney title='Banks' text='4/5 steps' image='placeholder.png' />
            <SwitchingJourney title='Banks' text='4/5 steps' image='placeholder.png' />
          </S.SwitchingJourney>
          {/* <Form /> */}
        </S.Content>
      </>
    </>
  )
}

export default Dashboard
