import type { NextPage } from 'next'
import Head from 'next/head'
import { Navigation } from '@components/Navigation/Navigation'
import { User } from '@components/User/User'
import { Hero } from '@components/Hero/Hero'
import { SmallCard } from '@components/SmallCard/SmallCard'
import * as S from '@modules/Dashboard/Dashboard.style'

type PageProps = {
  userData: any
}

const Dashboard: NextPage<PageProps> = ({ userData }: any) => {
  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <S.Dashboard>
        <Navigation />
        <S.Content>
          <User />
          <Hero />
          <S.SwitchingJourney>
            <S.Header>Switching Journeys</S.Header>
            <SmallCard title='Banks' text='4/5 steps' image='placeholder.png' />
            <SmallCard title='Banks' text='4/5 steps' image='placeholder.png' />
            <SmallCard title='Banks' text='4/5 steps' image='placeholder.png' />
          </S.SwitchingJourney>
          {/* <Form /> */}
        </S.Content>
        <S.Aside>aside</S.Aside>
      </S.Dashboard>
    </>
  )
}

export default Dashboard
