import { useEffect, useState } from 'react'
import Head from 'next/head'
import useSWR from 'swr'
import { useUser } from '@auth0/nextjs-auth0'
import { SocialPost } from '@components/SocialPost/SocialPost'
import { Card } from '@components/Card/Card'
import { Hero } from '@components/Hero/Hero'
import * as S from '@styles/common.style'

const Programs = (): JSX.Element => {
  // const { user: { sub = '' } = {}, isLoading = false } = useUser()

  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <S.Content>
        <Hero type='programs' />
        <S.ColumnContainer>
          <S.Column>
            <Card>
              <SocialPost school='lse' type='twitter' />
            </Card>
          </S.Column>
          <S.Column>
            <Card>
              <SocialPost school='lse' type='facebook' />
            </Card>
          </S.Column>
          <S.Column>
            <Card>
              <SocialPost school='lse' type='instagram' />
            </Card>
          </S.Column>
        </S.ColumnContainer>
      </S.Content>
    </>
  )
}

export default Programs
