import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
// import { useRouter } from 'next/router'
import { ErrorBoundary } from 'react-error-boundary'
import { Fallback } from '@components/Fallback/Fallback'
// import { Content } from '@styles/common.style'
import { Navigation } from './Navigation'
import * as S from './SignedOutLanding.style'

export const SignedOutLanding: NextPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <ErrorBoundary fallbackRender={({ error }) => <Fallback error={error?.message} />}>
        <S.Content>
          <Navigation />
          <S.BlockButton>
            <Link href='/programs'> Switch to a green bank</Link>
          </S.BlockButton>
        </S.Content>
      </ErrorBoundary>
    </>
  )
}
