import type { NextPage } from 'next'
import Head from 'next/head'
import { ErrorBoundary } from 'react-error-boundary'
import { Fallback } from '@components/Fallback/Fallback'
import { Footer } from './Footer'
import { Navigation } from './Navigation'
import * as S from './SignedOutLanding.style'

export const SignedOutLayout: NextPage<any> = ({ children }): JSX.Element => {
  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <ErrorBoundary fallbackRender={({ error }) => <Fallback error={error?.message} />}>
        <S.Content>
          <Navigation />
          {children}
          <Footer />
        </S.Content>
      </ErrorBoundary>
    </>
  )
}
