export const bankConfig = [
  {
    accountTypes: ['personal'],
    route: 'starling',
    icon: 'starling',
    bank: 'Starling Bank',
    details: 'Best current account',
    score: '5',
    fee: '£0',
    project: 'Carbon Removal',
    projectLink: 'starlingProject',
    donation: 'Yes',
    features: ['app', 'savings', 'deposits'],
    meta: [
      `Starling Bank is co-founder of an industry initiative called TechZero - designed to measure and help reduce tech companies' impact on the climate. The bank has also stated that it will not invest in, or take money from, the fossil fuel (or fossil fuel-related) industry.`,
      'Switch It Score - 5/5',
      'High-Street Branches - No',
      'Desktop Banking - No',
      'Apple/Google Pay - Yes',
      'App Rating Android, Apple - 4.8',
      'Cash Deposit Facility - Yes, via the Post Office',
      'Savings Accounts - Yes',
      'Mortgages - No',
      'Positive Environmental Impact Investment Policy - No',
    ],
  },
  {
    accountTypes: ['personal'],
    route: 'monzo',
    icon: 'monzo',
    bank: 'Monzo',
    details: 'Best money managment features',
    score: '',
    fee: '£0',
    project: 'Watershed',
    projectLink: 'monzoProject',
    donation: 'No',
    features: ['app', 'savings', 'deposits'],
    meta: [
      `Monzo does not invest in fossil fuels and advertise this on its website. However, Monzo has currently not committed to <em>never</em> invest in fossil fuels; which is a deciding factor for our 5/5 rating. We are hoping to work closely with Monzo to take their investment policy up a notch, and your support will help us achieve this.`,
      'Switch It Score - 4/5',
      'High-Street Branches - No',
      'Desktop Banking - No',
      'Apple/Google Pay - Yes',
      'App Rating Android, Apple - 4.7',
      'Cash Deposit Facility - Yes, via PayPoint shops',
      'Savings Accounts - Yes, through third parties only',
      'Mortgages - No',
      'Positive Environmental Impact Investment Policy - No',
    ],
  },
  {
    accountTypes: ['personal'],
    route: 'triodos',
    icon: 'triodos',
    bank: 'Triodos Bank',
    details: 'Best environmental policy overall',
    score: '',
    fee: '£3',
    project: 'Sea Lanes',
    projectLink: 'triodosProject',
    donation: 'No',
    features: ['app', 'savings', 'deposits'],
    meta: [
      'Triodos Bank is strongly committed to environmentally friendly banking and has a clear focus on sustainability. In fact, its entire business model is based on having a positive climate impact. It is a certified B-Corp and has totally transparent information on all the positive impact projects they currently invest in on its website. ',
      'Switch It Score - 5/5',
      'High-Street Branches - No',
      'Desktop Banking - Yes',
      'Apple/Google Pay - No',
      'App Rating Android, Apple - 3.1',
      'Cash Deposit Facility - No',
      'Savings Accounts - Yes',
      'Mortgages - No',
      'Positive Environmental Impact Investment Policy - Yes',
    ],
  },
  {
    accountTypes: ['personal', 'student'],
    route: 'nationwide',
    icon: 'nationwide',
    bank: 'Nationwide',
    details: 'Best for in person banking',
    score: '',
    fee: '£0',
    project: 'Sustainable Housing',
    projectLink: 'nationwideProject',
    donation: 'No',
    features: ['branches', 'app', 'savings', 'deposits', 'mortgages'],
    meta: [
      'Nationwide does not invest money in the fossil fuel industry and has a stated commitment to not do so in the future. ',
      'Switch It Score - 5/5',
      'High-Street Branches - Yes',
      'Desktop Banking - Yes',
      'Apple/Google Pay - Yes',
      'App Rating Android, Apple - 4.5',
      'Cash Deposit Facility - Yes',
      'Savings Accounts - Yes',
      'Mortgages - Yes',
      'Positive Environmental Impact Investment Policy - No',
    ],
  },
]

export const accountFeatures = [
  {
    type: 'branches',
    text: 'Physical branches',
  },
  {
    type: 'app',
    text: 'Mobile app',
  },
  {
    type: 'savings',
    text: 'Savings account',
  },
  {
    type: 'deposits',
    text: 'International deposits',
  },
  {
    type: 'mortgages',
    text: 'Mortgages',
  },
]

export const accountTypes = ['personal', 'student']
