import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { ErrorBoundary } from 'react-error-boundary'
import { Card } from '@components/Card/Card'
import { Fallback } from '@components/Fallback/Fallback'
import * as S from '@modules/Resources/components/Article/Article.style'
import { Post } from '@pages/dashboard'
import { ArticleData, Data } from '../Articles/Articles.style'

const Article: NextPage<{ posts: Post[] }> = ({ posts }) => {
  const {
    query: { id },
  } = useRouter()
  const {
    title = '',
    text = '',
    created = '',
    mins,
    points,
  } = posts.find(({ id: postId }: { id: string }) => postId === id) as Pick<
    Post,
    'title' | 'text' | 'created' | 'mins' | 'points'
  >

  console.log('posts', posts)

  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <ErrorBoundary fallbackRender={({ error }) => <Fallback error={error?.message} />}>
        <S.Content>
          <Card column rowGap={40}>
            <S.ArticleContent>
              <S.Article>
                <S.PostTitle>{title}</S.PostTitle>
                <ArticleData>
                  <Data>
                    <Image src={'/icons/icon_clock.svg'} alt='' width={20} height={20} />
                    {mins}min
                  </Data>
                  <Data>
                    <Image src={'/icons/icon_star_blue.svg'} alt='' width={20} height={20} />+
                    {points}
                    pts
                  </Data>
                </ArticleData>
                {/* <S.PostDate>{created.substring(0, 15)}</S.PostDate> */}
                <S.PostText dangerouslySetInnerHTML={{ __html: text }} />
              </S.Article>
              <S.MoreArticles>
                <S.MoreArticlesHeader>More in Resources</S.MoreArticlesHeader>
                <S.ArticlesList>
                  {posts.map(({ id, title }) => {
                    return (
                      <S.MoreItem key={id}>
                        <S.ImageContainer>
                          <Link href={`/article/${id}`}>
                            <Image src={'/images/temp.png'} alt={title} width={82} height={82} />
                          </Link>
                        </S.ImageContainer>
                        <Link href={`/resources/article/${id}`}>
                          <S.Details>
                            <S.ArticleTitle>{title}</S.ArticleTitle>
                            <S.Date>{created.substring(0, 15)}</S.Date>
                          </S.Details>
                        </Link>
                      </S.MoreItem>
                    )
                  })}
                </S.ArticlesList>
              </S.MoreArticles>
            </S.ArticleContent>
          </Card>
        </S.Content>
      </ErrorBoundary>
    </>
  )
}

export default Article
