import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { ErrorBoundary } from 'react-error-boundary'
import { useDispatch, useSelector } from 'react-redux'
import { RootState } from '@state/store'
import { Fallback } from '@components/Fallback/Fallback'
import { Hero } from '@components/Hero/Hero'
import { Card } from '@components/Card/Card'
import * as S from '@styles/common.style'
import { News } from '@components/News/News'

export type Resource = {
  id: string
  type: string
  title: string
  summary: string
  resource: string
  isFeatured: boolean
}

export type ResourcesType = Resource[]

const Resources: NextPage<{ resources: ResourcesType }> = ({ resources }) => {
  const user = useSelector((state: RootState) => state.user)
  // const { profile: { sharingCodes = [] } = {} } = user

  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <ErrorBoundary fallbackRender={({ error }) => <Fallback error={error?.message} />}>
        <S.Content>
          <Hero type='resources' />
          <S.ColumnContainer>
            <S.Column>
              <Card>
                <News resources={resources} />
              </Card>
            </S.Column>
            <S.Column>
              <Card>content</Card>
            </S.Column>
            <S.Column>
              <Card>content</Card>
            </S.Column>
          </S.ColumnContainer>
        </S.Content>
      </ErrorBoundary>
    </>
  )
}

export default Resources
