import Head from 'next/head'
import { useRouter } from 'next/router'
import { ErrorBoundary } from 'react-error-boundary'
import { Accordion } from '@components/Accordion/Accordion'
import { ActionHeader } from '@components/ActionHeader/ActionHeader'
import { Button } from '@components/Button/Button'
import { Card } from '@components/Card/Card'
import { Fallback } from '@components/Fallback/Fallback'
import { Tabs } from '@components/Tabs/Tabs'
import { Tabs as StyledTabs } from '@components/Tabs/Tabs.style'
import * as S from '@styles/common.style'

const data = [
  {
    question: 'What is CASS',
    answer: 'Current Account Switching Service',
  },
  {
    question: 'What is CASS',
    answer: 'Current Account Switching Service',
  },
  {
    question: 'What is CASS',
    answer: 'Current Account Switching Service',
  },
]

const panels: [React.ReactNode, React.ReactNode, React.ReactNode, React.ReactNode] = [
  <Accordion key='accordion' data={data} />,
  <Accordion key='accordion' data={data} />,
  <Accordion key='accordion' data={data} />,
  <Accordion key='accordion' data={data} />,
]

const tabs: string[] = ['Our Research', 'Programs', 'Switching', 'General']

const Faqs = (): JSX.Element => {
  const { back } = useRouter()

  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <ErrorBoundary fallbackRender={({ error }) => <Fallback error={error?.message} />}>
        <S.Content>
          <Card column padded>
            <ActionHeader header='Help' />

            <S.TabsContainer>
              <StyledTabs>
                <Tabs tabs={tabs} panels={panels}></Tabs>
              </StyledTabs>
            </S.TabsContainer>

            <S.Buttons align='left'>
              <Button type='button' mode='secondary' onClick={() => back()}>
                Back
              </Button>
            </S.Buttons>
          </Card>
        </S.Content>
      </ErrorBoundary>
    </>
  )
}

export default Faqs
