import type { AppProps } from 'next/app'
import Head from 'next/head'
import { UserProvider } from '@auth0/nextjs-auth0'
import styled from '@emotion/styled'
import { Provider } from 'react-redux'
import { useRouter } from 'next/router'
import { store } from 'src/state/store'
import { Navigation } from '@components/Navigation/Navigation'
import { mediaQuery } from '@utils/functions'
import '@styles/globals.css'
import 'normalize.css'

const AppContent = styled.div<{ isSignUp: boolean }>`
  display: flex;
  flex-direction: column;
  padding: ${({ isSignUp }) => (isSignUp ? '0' : '20px')};
  min-height: 100vh;

  ${() => mediaQuery.laptop} {
    flex-direction: row;
  }
`

const App = ({ Component, pageProps }: AppProps) => {
  const { pathname } = useRouter()
  const isSignUp = pathname === '/'

  return (
    <UserProvider>
      <Provider store={store}>
        <Head>
          <title>SwitchIt</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
        </Head>

        <AppContent isSignUp={isSignUp}>
          {!isSignUp && <Navigation />}
          <Component {...pageProps} />
        </AppContent>
      </Provider>
    </UserProvider>
  )
}

export default App
