import type { AppProps } from 'next/app'
import { UserProvider } from '@auth0/nextjs-auth0'
import Head from 'next/head'
import { Provider } from 'react-redux'
import { PersistGate } from 'redux-persist/integration/react'
import { Layout } from '@components/Layout/Layout'
import { store, persistor } from 'src/state/store'
import 'normalize.css'
import '@styles/globals.css'

// PER PAGE
// desktop
// mobile
// error handling
// loading state ui
// page reload
// content
//
// referral journey

// AUTH0
// social media login
// edit email and pw in auth0
// pw page
// mobile

// FOR APP
// analytics
// Sentry
// lighthouse
// db backups
// security
// email
// accessibility

// TECH DEBT
// linting and linting on commit
// remove useEffects where poss
// upgrade to Next 13
// refetch on all landing pages
// mongodb compass
// split up switching styles
// dynamic import for drawer
// integrate suspense

//NTH
// cypress tests

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <UserProvider>
      <Provider store={store}>
        <Head>
          <title>SwitchIt</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
        </Head>
        <PersistGate loading={null} persistor={persistor}>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </PersistGate>
      </Provider>
    </UserProvider>
  )
}

export default App
