import type { NextPage } from 'next'
import Head from 'next/head'
import { ErrorBoundary } from 'react-error-boundary'
import { Fallback } from '@components/Fallback/Fallback'
import * as S from '@modules/Blog/Blog.style'

type PageProps = {
  title: string
  text: string
  created: string
}

const Blog: NextPage<{ post: PageProps }> = ({
  post: { title = '', text = '', created = '' } = {},
}) => {
  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <ErrorBoundary fallbackRender={({ error }) => <Fallback error={error?.message} />}>
        <S.Content>
          <S.BlogCard column>
            <S.PostTitle>{title}</S.PostTitle>
            <S.PostDate>{created.substring(0, 15)}</S.PostDate>
            <S.PostText dangerouslySetInnerHTML={{ __html: text }} />
          </S.BlogCard>
        </S.Content>
      </ErrorBoundary>
    </>
  )
}

export default Blog
