import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import useSWR from 'swr'
import { useUser } from '@auth0/nextjs-auth0'
import { User } from '@components/User/User'
import { Card } from '@components/Card/Card'
import { Hero } from '@components/Hero/Hero'
import { fetcher } from '@utils/functions'
import {
  SwitchingColumnContainer,
  SwitchingColumn,
  Header,
  StartJourneyContainer,
  StartJourney,
} from '@modules/Switching/Switching.style'
import * as S from '@styles/common.style'

const Switching = (): JSX.Element => {
  // const { user: { sub = '' } = {}, isLoading = false } = useUser()

  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <S.Content>
        <Hero type='switching' />
        <SwitchingColumnContainer>
          <SwitchingColumn>
            <Card column>
              <Header>Active Journeys</Header>
              <Card shadow>
                <StartJourneyContainer>
                  <Link href='/switching/selectBank'>
                    <StartJourney>
                      <Image src={'/icons/icon_plus.svg'} alt='' width={45} height={45} />
                      Start a Switching Journey
                    </StartJourney>
                  </Link>
                  <p>
                    Have multiple bank accounts? No problem!
                    <br /> {`We'll switch one at a time.`}
                  </p>
                </StartJourneyContainer>
              </Card>
            </Card>
          </SwitchingColumn>
          <S.Column>
            <Card stretch column>
              Completed Journeys
              <p>{`You haven't completed any journeys`}</p>
            </Card>
          </S.Column>
        </SwitchingColumnContainer>
      </S.Content>
    </>
  )
}

export default Switching
