import Head from 'next/head'
import { useRouter } from 'next/router'
import { Card } from '@components/Card/Card'
import { Content } from '@styles/common.style'
import { bankConfig } from '@utils/constants'
import { HeaderContainer, Header, Subheader, Section } from '@modules/Switching/PreSwitching.style'
import { useEffect, useState } from 'react'
import { BankFilters } from '@modules/Switching/BankFilters'
import { BanksTable } from '@modules/Switching/BanksTable'

const ActionChooseBank = (): JSX.Element => {
  const { push } = useRouter()
  const [bankData, setBankData] = useState(bankConfig)
  const [selectedAccountTypes, selectAccountType] = useState<string[]>([])
  const [selectedFeatures, selectFeatures] = useState<string[]>([])

  useEffect(() => {
    console.log('selectedAccountTypes', selectedAccountTypes)
    console.log(', selectedFeatures', selectedFeatures)
    if (!selectedAccountTypes.length && !selectedFeatures.length) {
      setBankData(bankConfig)
      return
    }

    const filteredBanks = bankConfig.filter(
      ({ accountTypes, features }: { accountTypes: string[]; features: any }) =>
        (selectedAccountTypes.length
          ? selectedAccountTypes.every((selectedAccountType: string) =>
              accountTypes.includes(selectedAccountType),
            )
          : true) &&
        (selectedFeatures.length
          ? selectedFeatures.every((selectedFeature: string) => features.includes(selectedFeature))
          : true),
    )

    setBankData(filteredBanks)
  }, [selectedAccountTypes, selectedFeatures])

  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <Content>
        <Card column padded>
          <HeaderContainer>
            <Header>Action Choose Your Bank</Header>
            <Subheader>{`We've found 4 switch-worthy banks for you`}</Subheader>
            <p>{`Banks can't buy spaces on our site. We recommend banks based on our strict internal standards for reducing the investment in fossil fuels. Find out more here`}</p>
          </HeaderContainer>

          <Section>
            <BankFilters
              selectedAccountTypes={selectedAccountTypes}
              selectedFeatures={selectedFeatures}
              selectAccountType={selectAccountType}
              selectFeatures={selectFeatures}
            />
            <BanksTable bankData={bankData} />
          </Section>
        </Card>
      </Content>
    </>
  )
}

export default ActionChooseBank
