import Head from 'next/head'
import { useRouter } from 'next/router'
import { Card } from '@components/Card/Card'
import { Content } from '@styles/common.style'
import { ProgressBar } from '@components/ProgressBar/ProgressBar'
import { Button } from '@components/Button/Button'
import * as S from '@pages/switching/Switching.style'
import Link from 'next/link'

const ChooseJourney = (): JSX.Element => {
  const { replace } = useRouter()

  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <Content>
        <Card column padded>
          <S.HeaderContainer>
            <S.Header>{`Let's figure out the best journey for you.`}</S.Header>
            <S.Subheader>{`Please select which of the following best describes what you'd like to do.`}</S.Subheader>
          </S.HeaderContainer>

          <S.Section>
            <S.ChooseJourneyLink isActive>
              <Link href='/switching/selectaction'>
                {` Ready to switch or can't switch but still want to open a green bank account`}
              </Link>
            </S.ChooseJourneyLink>
            <S.ChooseJourneyLink>
              <Link href='/switching/selectaction'>
                Not ready to switch but still want to use my voice to act
              </Link>
            </S.ChooseJourneyLink>
          </S.Section>

          <S.Section>
            {/* <S.ButtonContainer>
              <Button
                type='button'
                onClick={() => {
                  replace('/switching/selectaction')
                }}
              >
                Next
              </Button>
            </S.ButtonContainer> */}
            <ProgressBar step={3} />
          </S.Section>
        </Card>
      </Content>
    </>
  )
}

export default ChooseJourney
