import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Image from 'next/image'
import { useDispatch } from 'react-redux'
import { Card } from '@components/Card/Card'
import { Content } from '@styles/common.style'
import { ProgressBar } from '@components/ProgressBar/ProgressBar'
import { Button } from '@components/Button/Button'
import { actionsConfig, actionText } from '@utils/constants'
import { useRef, useState } from 'react'
import { ActionHeader } from '@components/ActionHeader/ActionHeader'
import { SwitchingColumnContainer, SwitchingColumn } from '@modules/Switching/Switching.style'
import * as S from '@modules/Switching/PreSwitching.style'
import { setActionCard } from '@state/actionCard/actionCardSlice'

type ActionsConfig = typeof actionsConfig[0]

const SelectAction = (): JSX.Element => {
  const { push } = useRouter()
  const dispatch = useDispatch()
  const [selectedRoute, setRoute] = useState(actionsConfig[0].route)
  const [currentAction, setAction] = useState<ActionsConfig | null>(null)

  const selectAction = (index: number) => () => {
    setRoute(actionsConfig[index].route)
    setAction(actionsConfig[index])
    dispatch(setActionCard(index))
  }

  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <Content>
        <SwitchingColumnContainer>
          <SwitchingColumn>
            <Card column padded>
              <ActionHeader
                header={`Let's design your switching journey, and maximise your impact`}
                subHeader={`Select which of the following actions you'd like to take. The more actions completed, the bigger the impact.`}
              />

              <S.Section>
                <S.ActionSelector>
                  {actionsConfig.map(({ text, icon, duration, pointsEarned, route }, i: number) => (
                    <S.Item key={route} isActive={icon === currentAction?.icon}>
                      <S.LinkContainer onClick={selectAction(i)}>
                        <Image src={`/icons/icon_${icon}.svg`} alt='' width={70} height={70} />
                        <h3>{text}</h3>
                        <S.MetaData>
                          <span>{duration}min</span>
                          <span>{pointsEarned}pts</span>
                        </S.MetaData>
                      </S.LinkContainer>
                    </S.Item>
                  ))}
                </S.ActionSelector>
              </S.Section>

              <S.Section>
                <S.ButtonContainer>
                  <Button
                    type='button'
                    disabled={!currentAction}
                    onClick={() => {
                      // push(selectedRoute)
                      push('/switching/start-journey')
                    }}
                  >
                    Next
                  </Button>
                </S.ButtonContainer>
                <ProgressBar step={4} />
              </S.Section>
            </Card>
          </SwitchingColumn>
        </SwitchingColumnContainer>
      </Content>
    </>
  )
}

export default SelectAction
