import Head from 'next/head'
import { Card } from '@components/Card/Card'
import { Content } from '@styles/common.style'
import * as S from '@modules/Switching/PreSwitching.style'
import BankFinder from './BankFinder'

const SelectBank = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>SwitchIt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <Content>
        <Card column>
          <S.Header>{`First, let's see how your bank stacks up...`}</S.Header>
          <BankFinder />
        </Card>
      </Content>
    </>
  )
}

export default SelectBank
